### ISSUE TITLE
Could you make it so birds spawn on any biome? 

### ISSUE THREAD

**Issue by fbklas** [Tomate0613/birds-boids#8]
Birds spawning only in forests is very limiting! I'm trying to change the code myself but i'm a noob and it isn't working.

**Comment by darceno** [comment]
A config file for biome filters would be really nice.

**Comment by BioMasterZap** [comment]
I came here to suggest the same thing. It could work as a tag so you could add or change biomes with a data pack. It would at least be nice to see them in the forest variants like birch and flower, but I'd also like to add them to some of the modded forests in my pack.

**Comment by Tomate0613** [comment]
They will be datadriven in the next update, but I only added "flower_forest" as default, since I don't really think they fit into the other forest biomes.

Adding other biomes to the list should be as easy as creating a datapack with
`data/birdsboids/tags/worldgen/biome/spawns_birds.json` and adding the biomes there
```json
{
  "replace": "false"
  "values": [
    "minecraft:birch_forest"
  ]
}
```
